"""empty message

Revision ID: 0fbad3be45c5
Revises: 54b40b110373
Create Date: 2025-06-03 12:36:20.980143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fbad3be45c5'
down_revision = '54b40b110373'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_name', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('pasword', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('date', sa.DateTime(timezone=True), nullable=False))
        batch_op.drop_constraint('user_address_key', type_='unique')
        batch_op.drop_constraint('user_username_key', type_='unique')
        batch_op.create_unique_constraint(None, ['pasword'])
        batch_op.create_unique_constraint(None, ['user_name'])
        batch_op.drop_column('username')
        batch_op.drop_column('address')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('username', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('user_username_key', ['username'])
        batch_op.create_unique_constraint('user_address_key', ['address'])
        batch_op.drop_column('date')
        batch_op.drop_column('pasword')
        batch_op.drop_column('user_name')

    # ### end Alembic commands ###
