"""empty message

Revision ID: 1fd2abf02705
Revises: 1ab5e20a5b32
Create Date: 2025-06-03 13:37:57.989269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fd2abf02705'
down_revision = '1ab5e20a5b32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favourite', schema=None) as batch_op:
        batch_op.add_column(sa.Column('login_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'login', ['login_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favourite', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('login_id')

    # ### end Alembic commands ###
