"""empty message

Revision ID: 34faa6e7a2d9
Revises: bb5a1ec2f2ad
Create Date: 2025-06-03 13:32:21.381355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34faa6e7a2d9'
down_revision = 'bb5a1ec2f2ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Planet_name', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('Planet_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('planet')
    # ### end Alembic commands ###
